### ISSUE TITLE
crash!help

### ISSUE THREAD

**Issue by zte-zhangmingxing** [alecthomas/gozmq#104]
zmq4.1.3 +alecthomas/gozmq,when i create 1015th socket ,program is crash.

// TestZmq

package main

import (
	MyZmq "ddd/gozmq-master"
	"fmt"
	"math/rand"
	"runtime"
	_ "strings"
	"time"
)

func main() {
	M2Context, _ := MyZmq.NewContext()
	total := int32(0)
	go M2ManagerStarUp(M2Context, &total)
	msg1 := make([]byte, 800)
	channel1 := make(chan string)
	for i := 0; i < 800; i++ {
		msg1[i] = 'a'
	}
	for i := 0; i < 1016; i++ {
		time.Sleep(1 * time.Millisecond)
		go M2ApWorkerStarUp(M2Context, rand.Int31(), &msg1, channel1)
		fmt.Printf("main StarUp have made goroutine=%d\n", i)
	}
	fmt.Printf("main StarUp will make goroutine=%d\n", runtime.NumGoroutine())
	time.Sleep(30 * time.Second)
    fmt.Printf("recv msg=%d \n", total)
}

func M2ApWorkerStarUp(Context *MyZmq.Context, id int32, msg *[]byte, chann chan string) {

	M2ApWorkerSocket, _ := Context.NewSocket(MyZmq.DEALER)
	M2ApWorkerSocket.SetSockOptInt(MyZmq.SNDHWM, 1000)
	M2ApWorkerSocket.SetSockOptInt(MyZmq.RCVHWM, 1000)
	M2ApPID := fmt.Sprintf("%d", id)
	M2ApWorkerSocket.SetIdentity(M2ApPID)
	fmt.Printf("SetIdentity %d\n", id)
	M2ApWorkerSocket.Connect("inproc://M2")
	for {
		<-chann
	}

}

func M2ManagerStarUp(Context *MyZmq.Context, total *int32) error {

	fmt.Println("M2Manager Init")

	M2ManagerEndPointSocket, _ := Context.NewSocket(MyZmq.ROUTER)
	M2ManagerEndPointSocket.SetSockOptInt(MyZmq.SNDHWM, 0)
	M2ManagerEndPointSocket.SetSockOptInt(MyZmq.RCVHWM, 0)

	M2ManagerEndPointSocket.Bind("inproc://M2")

	for {

		parts, err := M2ManagerEndPointSocket.RecvMultipart(0)
		if err != nil {
			print(err)
		}
		_ = parts
		(*total)++

	}

	return nil

}

main StarUp have made goroutine=1014
SetIdentity 635784984
main StarUp have made goroutine=1015
main StarUp will make goroutine=1021
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x8 pc=0x427299]

goroutine 1021 [running]:
runtime.panic(0x4ad3c0, 0x79eb68)
        /usr/lib/go/src/pkg/runtime/panic.c:266 +0xb6
ddd/gozmq-master.(*Socket).SetSockOptInt(0x0, 0x17, 0x3e8, 0x7f3a2aeae070, 0x18)
        /home/go/src/ddd/gozmq-master/zmq.go:234 +0x39
main.M2ApWorkerStarUp(0xc21001f2a0, 0x119414e5, 0xc21004b020, 0xc21003a060)
        /home/go/src/ddd/ddd.go:36 +0x60
created by main.main
        /home/go/src/ddd/ddd.go:25 +0x160

**Comment by alecthomas** [comment]
This package is not being developed anymore, and I don't have time to dig into a bug like this. You would be better off switching to the other zmq packages as referenced on the main page.
